sonar.projectKey=irenejaramillo076-cpu_biblioteca-virtual
sonar.organization=irenejaramillo076-cpu

sonar.sources=backend,frontend
sonar.tests=tests
sonar.exclusions=tests/**,backend/node_modules/**,backend/coverage/**,reports/**,test-results/**
sonar.test.inclusions=tests/unit/**/*.js,tests/e2e/**/*.js,tests/e2e/**/*.feature
sonar.coverage.exclusions=frontend/**,backend/server.js,backend/database/**,backend/routes/categorias.js,backend/routes/prestamos.js,backend/routes/usuarios.js
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
